### ISSUE TITLE
unban.js command error

### ISSUE THREAD

**Issue by henryglazt** [AllanGame/discord-moderator-bot#5]
when I run the command /unban <@username> <reason>, and I get an error like this, can you please help me fix this problem?

(node:1012) UnhandledPromiseRejectionWarning: DiscordAPIError: 404: Not Found
    at RequestHandler.execute (E:\Project\privx\node_modules\discord.js\src\rest\RequestHandler.js:154:13)      
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async RequestHandler.push (E:\Project\privx\node_modules\discord.js\src\rest\RequestHandler.js:39:14)    
    at async UserManager.fetch (E:\Project\privx\node_modules\discord.js\src\managers\UserManager.js:67:18)     
    at async UnbanCommand.run (E:\Project\privx\src\commands\moderation\UnbanCommand.js:13:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1012) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1012) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.``

**Comment by AllanGame** [comment]
I'll update the bot in a few hours and fix it

**Comment by AllanGame** [comment]
fixed with the new version
